<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('seasons')->insert([
            ["id"=>1,"name"=>'{"en":"Flat"}'],
            ["id"=>2,"name"=>'{"en":"Low"}'],
            ["id"=>3,"name"=>'{"en":"Shoulder"}'],
            ["id"=>4,"name"=>'{"en":"High"}'],
            ["id"=>5,"name"=>'{"en":"Peak"}'],
            ["id"=>6,"name"=>'{"en":"Winter Promotion"}'],
            ["id"=>7,"name"=>'{"en":"Summer Promotion"}'],
        ]);

        DB::table('stars')->insert([
            ["id"=>1,"name"=>'{"en":"3*"}'],
            ["id"=>2,"name"=>'{"en":"4*"}'],
            ["id"=>3,"name"=>'{"en":"5*"}'],
        ]);

        DB::table('currencies')->insert([
            ["id"=>1,"name"=>'{"en":"Jordanian Dinar"}','symbol'=>'JD','exchange_rate_to_usd'=>0.73],
        ]);

        DB::table('regions')->insert([
            ["id"=>1,"name"=>'{"en":"None"}'],
            ["id"=>2,"name"=>'{"en":"Arab States"}'],
            ["id"=>3,"name"=>'{"en":"Africa"}'],
            ["id"=>4,"name"=>'{"en":"Europe"}'],
            ["id"=>5,"name"=>'{"en":"CIS"}'],
            ["id"=>6,"name"=>'{"en":"North America"}'],
            ["id"=>7,"name"=>'{"en":"South/Latin America"}'],
            ["id"=>8,"name"=>'{"en":"Others"}'],
            ["id"=>9,"name"=>'{"en":"Jerusalem"}'],
            ["id"=>10,"name"=>'{"en":"Middle East"}'],
            ["id"=>11,"name"=>'{"en":"USA"}'],
        ]);

        DB::table('countries')->insert([
            ["code"=>"AE", "name"=>'{"en":"United Arab Emirates"}',"region_id"=>2,],
            ["code"=>"AF", "name"=>'{"en":"Afghanistan"}',"region_id"=>1,],
            ["code"=>"AG", "name"=>'{"en":"Antigua And Barbuda"}',"region_id"=>7,],
            ["code"=>"AI", "name"=>'{"en":"Anguilla"}',"region_id"=>7,],
            ["code"=>"AL", "name"=>'{"en":"Albania"}',"region_id"=>4,],
            ["code"=>"AM", "name"=>'{"en":"Armenia"}',"region_id"=>5,],
            ["code"=>"AN", "name"=>'{"en":"Netherlands Antilles"}',"region_id"=>7,],
            ["code"=>"AO", "name"=>'{"en":"Angola"}',"region_id"=>3,],
            ["code"=>"AR", "name"=>'{"en":"Argentina"}',"region_id"=>7,],
            ["code"=>"AS", "name"=>'{"en":"America"}',"region_id"=>11,],
            ["code"=>"AT", "name"=>'{"en":"Austria"}',"region_id"=>4,],
            ["code"=>"AU", "name"=>'{"en":"Australia"}',"region_id"=>1,],
            ["code"=>"AW", "name"=>'{"en":"Aruba"}',"region_id"=>7,],
            ["code"=>"BA", "name"=>'{"en":"Bosnia And Herzegovina"}',"region_id"=>4,],
            ["code"=>"BB", "name"=>'{"en":"Barbados"}',"region_id"=>7,],
            ["code"=>"BD", "name"=>'{"en":"Bangladesh"}',"region_id"=>1,],
            ["code"=>"BE", "name"=>'{"en":"Belgium"}',"region_id"=>4,],
            ["code"=>"BF", "name"=>'{"en":"Burkina Faso"}',"region_id"=>3,],
            ["code"=>"BG", "name"=>'{"en":"Bulgaria"}',"region_id"=>4,],
            ["code"=>"BH", "name"=>'{"en":"Bahrain"}',"region_id"=>2,],
            ["code"=>"BI", "name"=>'{"en":"Burundi"}',"region_id"=>3,],
            ["code"=>"BJ", "name"=>'{"en":"Benin"}',"region_id"=>3,],
            ["code"=>"BM", "name"=>'{"en":"Bermuda"}',"region_id"=>6,],
            ["code"=>"BN", "name"=>'{"en":"Brunei Darussalam"}',"region_id"=>1,],
            ["code"=>"BO", "name"=>'{"en":"Bolivia"}',"region_id"=>7,],
            ["code"=>"BR", "name"=>'{"en":"Brazil"}',"region_id"=>7,],
            ["code"=>"BS", "name"=>'{"en":"Bahamas"}',"region_id"=>7,],
            ["code"=>"BT", "name"=>'{"en":"Bhutan"}',"region_id"=>1,],
            ["code"=>"BW", "name"=>'{"en":"Botswana"}',"region_id"=>3,],
            ["code"=>"BY", "name"=>'{"en":"Belarus"}',"region_id"=>5,],
            ["code"=>"BZ", "name"=>'{"en":"Belize"}',"region_id"=>7,],
            ["code"=>"CA", "name"=>'{"en":"Canada"}',"region_id"=>6,],
            ["code"=>"CD", "name"=>'{"en":"Democratic Republic Of Congo"}',"region_id"=>3,],
            ["code"=>"CF", "name"=>'{"en":"Central African Republic"}',"region_id"=>3,],
            ["code"=>"CG", "name"=>'{"en":"Congo"}',"region_id"=>3,],
            ["code"=>"CH", "name"=>'{"en":"Switzerland"}',"region_id"=>4,],
            ["code"=>"CI", "name"=>'{"en":"Cote D\'Ivoire"}',"region_id"=>3,],
            ["code"=>"CK", "name"=>'{"en":"Cook Islands"}',"region_id"=>1,],
            ["code"=>"CL", "name"=>'{"en":"Chile"}',"region_id"=>7,],
            ["code"=>"CM", "name"=>'{"en":"Cameroon"}',"region_id"=>3,],
            ["code"=>"CN", "name"=>'{"en":"China"}',"region_id"=>1,],
            ["code"=>"CO", "name"=>'{"en":"Colombia"}',"region_id"=>7,],
            ["code"=>"CR", "name"=>'{"en":"Costa Rica"}',"region_id"=>7,],
            ["code"=>"CU", "name"=>'{"en":"Cuba"}',"region_id"=>7,],
            ["code"=>"CV", "name"=>'{"en":"Cape Verde"}',"region_id"=>3,],
            ["code"=>"CY", "name"=>'{"en":"Cyprus"}',"region_id"=>4,],
            ["code"=>"CZ", "name"=>'{"en":"Czech Republic"}',"region_id"=>4,],
            ["code"=>"DE", "name"=>'{"en":"Germany"}',"region_id"=>4,],
            ["code"=>"DJ", "name"=>'{"en":"Djibouti"}',"region_id"=>2,],
            ["code"=>"DK", "name"=>'{"en":"Denmark"}',"region_id"=>4,],
            ["code"=>"DO", "name"=>'{"en":"Dominican Republic"}',"region_id"=>7,],
            ["code"=>"DZ", "name"=>'{"en":"Algeria"}',"region_id"=>2,],
            ["code"=>"EC", "name"=>'{"en":"Ecuador"}',"region_id"=>7,],
            ["code"=>"EE", "name"=>'{"en":"Estonia"}',"region_id"=>4,],
            ["code"=>"EG", "name"=>'{"en":"Egypt"}',"region_id"=>2,],
            ["code"=>"ES", "name"=>'{"en":"Spain"}',"region_id"=>4,],
            ["code"=>"ET", "name"=>'{"en":"Ethiopia"}',"region_id"=>3,],
            ["code"=>"FI", "name"=>'{"en":"Finland"}',"region_id"=>4,],
            ["code"=>"FJ", "name"=>'{"en":"Fiji"}',"region_id"=>1,],
            ["code"=>"FM", "name"=>'{"en":"Micronesia"}',"region_id"=>8,],
            ["code"=>"FO", "name"=>'{"en":"Faroe Islands"}',"region_id"=>4,],
            ["code"=>"FR", "name"=>'{"en":"France"}',"region_id"=>4,],
            ["code"=>"GA", "name"=>'{"en":"Gabon"}',"region_id"=>3,],
            ["code"=>"GB", "name"=>'{"en":"Scotland, United Kingdom"}',"region_id"=>4,],
            ["code"=>"GD", "name"=>'{"en":"Grenada"}',"region_id"=>7,],
            ["code"=>"GE", "name"=>'{"en":"Georgia"}',"region_id"=>5,],
            ["code"=>"GF", "name"=>'{"en":"French Guiana"}',"region_id"=>7,],
            ["code"=>"GH", "name"=>'{"en":"Ghana"}',"region_id"=>3,],
            ["code"=>"GI", "name"=>'{"en":"Gibraltar"}',"region_id"=>4,],
            ["code"=>"GL", "name"=>'{"en":"Greenland"}',"region_id"=>4,],
            ["code"=>"GM", "name"=>'{"en":"Gambia"}',"region_id"=>3,],
            ["code"=>"GN", "name"=>'{"en":"Guinea"}',"region_id"=>3,],
            ["code"=>"GP", "name"=>'{"en":"Guadeloupe"}',"region_id"=>7,],
            ["code"=>"GQ", "name"=>'{"en":"Equatorial Guinea"}',"region_id"=>3,],
            ["code"=>"GR", "name"=>'{"en":"Greece"}',"region_id"=>4,],
            ["code"=>"GT", "name"=>'{"en":"Guatemala"}',"region_id"=>7,],
            ["code"=>"GU", "name"=>'{"en":"Guam"}',"region_id"=>1,],
            ["code"=>"GW", "name"=>'{"en":"Guinea-Bissau"}',"region_id"=>3,],
            ["code"=>"GY", "name"=>'{"en":"Guyana"}',"region_id"=>7,],
            ["code"=>"HK", "name"=>'{"en":"Hong Kong"}',"region_id"=>1,],
            ["code"=>"HN", "name"=>'{"en":"Honduras"}',"region_id"=>7,],
            ["code"=>"HR", "name"=>'{"en":"Croatia"}',"region_id"=>4,],
            ["code"=>"HT", "name"=>'{"en":"Haiti"}',"region_id"=>7,],
            ["code"=>"HU", "name"=>'{"en":"Hungary"}',"region_id"=>4,],
            ["code"=>"ID", "name"=>'{"en":"Indonesia"}',"region_id"=>1,],
            ["code"=>"IE", "name"=>'{"en":"Ireland"}',"region_id"=>4,],
            ["code"=>"IL", "name"=>'{"en":"Israel"}',"region_id"=>4,],
            ["code"=>"IN", "name"=>'{"en":"India"}',"region_id"=>1,],
            ["code"=>"IQ", "name"=>'{"en":"Iraq"}',"region_id"=>2,],
            ["code"=>"IR", "name"=>'{"en":"Iran"}',"region_id"=>1,],
            ["code"=>"IS", "name"=>'{"en":"Iceland"}',"region_id"=>4,],
            ["code"=>"IT", "name"=>'{"en":"Italy"}',"region_id"=>4,],
            ["code"=>"JM", "name"=>'{"en":"Jamaica"}',"region_id"=>7,],
            ["code"=>"JO", "name"=>'{"en":"Jordan"}',"region_id"=>2,],
            ["code"=>"JP", "name"=>'{"en":"Japan"}',"region_id"=>1,],
            ["code"=>"KE", "name"=>'{"en":"Kenya"}',"region_id"=>3,],
            ["code"=>"KH", "name"=>'{"en":"Cambodia"}',"region_id"=>1,],
            ["code"=>"KI", "name"=>'{"en":"Kiribati"}',"region_id"=>1,],
            ["code"=>"KM", "name"=>'{"en":"Comoros"}',"region_id"=>2,],
            ["code"=>"KN", "name"=>'{"en":"Saint Kitts and Nevis"}',"region_id"=>7,],
            ["code"=>"KR", "name"=>'{"en":"Korea"}',"region_id"=>1,],
            ["code"=>"KW", "name"=>'{"en":"Kuwait"}',"region_id"=>2,],
            ["code"=>"KY", "name"=>'{"en":"Cayman Islands"}',"region_id"=>7,],
            ["code"=>"KZ", "name"=>'{"en":"Kazakhstan"}',"region_id"=>5,],
            ["code"=>"LA", "name"=>'{"en":"Laos"}',"region_id"=>1,],
            ["code"=>"LB", "name"=>'{"en":"Lebanon"}',"region_id"=>2,],
            ["code"=>"LC", "name"=>'{"en":"Saint Lucia"}',"region_id"=>7,],
            ["code"=>"LK", "name"=>'{"en":"Sri Lanka"}',"region_id"=>1,],
            ["code"=>"LR", "name"=>'{"en":"Liberia"}',"region_id"=>3,],
            ["code"=>"LS", "name"=>'{"en":"Lesotho"}',"region_id"=>3,],
            ["code"=>"LT", "name"=>'{"en":"Lithuania"}',"region_id"=>4,],
            ["code"=>"LU", "name"=>'{"en":"Luxembourg"}',"region_id"=>4,],
            ["code"=>"LV", "name"=>'{"en":"Latvia"}',"region_id"=>4,],
            ["code"=>"LY", "name"=>'{"en":"Libya"}',"region_id"=>2,],
            ["code"=>"MA", "name"=>'{"en":"Morocco"}',"region_id"=>2,],
            ["code"=>"ME", "name"=>'{"en":"Montenegro"}',"region_id"=>4,],
            ["code"=>"MG", "name"=>'{"en":"Madagascar"}',"region_id"=>3,],
            ["code"=>"MK", "name"=>'{"en":"Macedonia"}',"region_id"=>4,],
            ["code"=>"ML", "name"=>'{"en":"Mali"}',"region_id"=>3,],
            ["code"=>"MM", "name"=>'{"en":"Myanmar"}',"region_id"=>1,],
            ["code"=>"MN", "name"=>'{"en":"Mongolia"}',"region_id"=>1,],
            ["code"=>"MO", "name"=>'{"en":"Macau"}',"region_id"=>1,],
            ["code"=>"MP", "name"=>'{"en":"Northern Mariana Islands"}',"region_id"=>1,],
            ["code"=>"MQ", "name"=>'{"en":"Martinique"}',"region_id"=>7,],
            ["code"=>"MR", "name"=>'{"en":"Mauritania"}',"region_id"=>2,],
            ["code"=>"MT", "name"=>'{"en":"Malta"}',"region_id"=>4,],
            ["code"=>"MU", "name"=>'{"en":"Mauritius"}',"region_id"=>3,],
            ["code"=>"MV", "name"=>'{"en":"Maldives"}',"region_id"=>1,],
            ["code"=>"MW", "name"=>'{"en":"Malawi"}',"region_id"=>3,],
            ["code"=>"MX", "name"=>'{"en":"Mexico"}',"region_id"=>7,],
            ["code"=>"MY", "name"=>'{"en":"Malaysia"}',"region_id"=>1,],
            ["code"=>"MZ", "name"=>'{"en":"Mozambique"}',"region_id"=>3,],
            ["code"=>"NA", "name"=>'{"en":"Namibia"}',"region_id"=>3,],
            ["code"=>"NC", "name"=>'{"en":"New Caledonia"}',"region_id"=>1,],
            ["code"=>"NE", "name"=>'{"en":"Niger"}',"region_id"=>3,],
            ["code"=>"NF", "name"=>'{"en":"Norfolk Island"}',"region_id"=>1,],
            ["code"=>"NG", "name"=>'{"en":"Nigeria"}',"region_id"=>3,],
            ["code"=>"NI", "name"=>'{"en":"Nicaragua"}',"region_id"=>7,],
            ["code"=>"NL", "name"=>'{"en":"Netherlands"}',"region_id"=>4,],
            ["code"=>"NO", "name"=>'{"en":"Norway"}',"region_id"=>4,],
            ["code"=>"NP", "name"=>'{"en":"Nepal"}',"region_id"=>1,],
            ["code"=>"NZ", "name"=>'{"en":"New Zealand"}',"region_id"=>1,],
            ["code"=>"OM", "name"=>'{"en":"Oman"}',"region_id"=>2,],
            ["code"=>"PA", "name"=>'{"en":"Panama"}',"region_id"=>7,],
            ["code"=>"PE", "name"=>'{"en":"Peru"}',"region_id"=>7,],
            ["code"=>"PF", "name"=>'{"en":"French Polynesia"}',"region_id"=>1,],
            ["code"=>"PG", "name"=>'{"en":"Papua New Guinea"}',"region_id"=>1,],
            ["code"=>"PH", "name"=>'{"en":"Philippines"}',"region_id"=>1,],
            ["code"=>"PK", "name"=>'{"en":"Pakistan"}',"region_id"=>1,],
            ["code"=>"PL", "name"=>'{"en":"Poland"}',"region_id"=>4,],
            ["code"=>"PM", "name"=>'{"en":"St. Pierre And Miquelon"}',"region_id"=>6,],
            ["code"=>"PR", "name"=>'{"en":"Puerto Rico"}',"region_id"=>7,],
            ["code"=>"PT", "name"=>'{"en":"Portugal"}',"region_id"=>4,],
            ["code"=>"PY", "name"=>'{"en":"Paraguay"}',"region_id"=>7,],
            ["code"=>"QA", "name"=>'{"en":"Qatar"}',"region_id"=>2,],
            ["code"=>"RE", "name"=>'{"en":"Reunion"}',"region_id"=>1,],
            ["code"=>"RO", "name"=>'{"en":"Romania"}',"region_id"=>4,],
            ["code"=>"RS", "name"=>'{"en":"Serbia"}',"region_id"=>4,],
            ["code"=>"RU", "name"=>'{"en":"Russian Federation"}',"region_id"=>4,],
            ["code"=>"RW", "name"=>'{"en":"Rwanda"}',"region_id"=>3,],
            ["code"=>"SA", "name"=>'{"en":"Saudi Arabia"}',"region_id"=>2,],
            ["code"=>"SB", "name"=>'{"en":"Solomon Islands"}',"region_id"=>1,],
            ["code"=>"SC", "name"=>'{"en":"Seychelles"}',"region_id"=>3,],
            ["code"=>"SD", "name"=>'{"en":"Sudan"}',"region_id"=>2,],
            ["code"=>"SE", "name"=>'{"en":"Sweden"}',"region_id"=>4,],
            ["code"=>"SG", "name"=>'{"en":"Singapore"}',"region_id"=>1,],
            ["code"=>"SI", "name"=>'{"en":"Slovenia"}',"region_id"=>4,],
            ["code"=>"SK", "name"=>'{"en":"Slovakia"}',"region_id"=>4,],
            ["code"=>"SL", "name"=>'{"en":"Sierra Leone"}',"region_id"=>3,],
            ["code"=>"SN", "name"=>'{"en":"Senegal"}',"region_id"=>3,],
            ["code"=>"SO", "name"=>'{"en":"Somalia"}',"region_id"=>2,],
            ["code"=>"SR", "name"=>'{"en":"Suriname"}',"region_id"=>7,],
            ["code"=>"ST", "name"=>'{"en":"Sao Tome and Principe"}',"region_id"=>3,],
            ["code"=>"SV", "name"=>'{"en":"El Salvador"}',"region_id"=>7,],
            ["code"=>"SY", "name"=>'{"en":"Syria"}',"region_id"=>2,],
            ["code"=>"SZ", "name"=>'{"en":"Swaziland"}',"region_id"=>3,],
            ["code"=>"TD", "name"=>'{"en":"Chad"}',"region_id"=>3,],
            ["code"=>"TG", "name"=>'{"en":"Togo"}',"region_id"=>3,],
            ["code"=>"TH", "name"=>'{"en":"Thailand"}',"region_id"=>1,],
            ["code"=>"TJ", "name"=>'{"en":"Tajikistan"}',"region_id"=>5,],
            ["code"=>"TM", "name"=>'{"en":"Turkmenistan"}',"region_id"=>5,],
            ["code"=>"TN", "name"=>'{"en":"Tunisia"}',"region_id"=>2,],
            ["code"=>"TO", "name"=>'{"en":"Tonga"}',"region_id"=>1,],
            ["code"=>"TK", "name"=>'{"en":"Turkey"}',"region_id"=>4,],
            ["code"=>"TT", "name"=>'{"en":"Trinidad And Tobago"}',"region_id"=>7,],
            ["code"=>"TW", "name"=>'{"en":"Taiwan"}',"region_id"=>1,],
            ["code"=>"TZ", "name"=>'{"en":"Tanzania"}',"region_id"=>3,],
            ["code"=>"UA", "name"=>'{"en":"Ukraine"}',"region_id"=>5,],
            ["code"=>"UG", "name"=>'{"en":"Uganda"}',"region_id"=>3,],
            ["code"=>"UK", "name"=>'{"en":"United Kingdom"}',"region_id"=>4,],
            ["code"=>"US", "name"=>'{"en":"United States"}',"region_id"=>6,],
            ["code"=>"UY", "name"=>'{"en":"Uruguay"}',"region_id"=>7,],
            ["code"=>"UZ", "name"=>'{"en":"Uzbekistan"}',"region_id"=>5,],
            ["code"=>"VC", "name"=>'{"en":"Saint Vincent And The Grenadines"}',"region_id"=>7,],
            ["code"=>"VE", "name"=>'{"en":"Venezuela"}',"region_id"=>7,],
            ["code"=>"VG", "name"=>'{"en":"British Virgin Islands"}',"region_id"=>8,],
            ["code"=>"VI", "name"=>'{"en":"Virgin Islands, US"}',"region_id"=>6,],
            ["code"=>"VN", "name"=>'{"en":"Viet Nam"}',"region_id"=>1,],
            ["code"=>"VU", "name"=>'{"en":"Vanuatu"}',"region_id"=>1,],
            ["code"=>"WF", "name"=>'{"en":"Wallis and Futuna Islands"}',"region_id"=>1,],
            ["code"=>"WS", "name"=>'{"en":"Samoa"}',"region_id"=>1,],
            ["code"=>"YE", "name"=>'{"en":"Yemen"}',"region_id"=>2,],
            ["code"=>"ZA", "name"=>'{"en":"South Africa"}',"region_id"=>3,],
            ["code"=>"ZM", "name"=>'{"en":"Zambia"}',"region_id"=>3,],
            ["code"=>"ZR", "name"=>'{"en":"Zaire"}',"region_id"=>3,],
            ["code"=>"ZW", "name"=>'{"en":"Zimbabwe"}',"region_id"=>3,],
            ["code"=>"JR", "name"=>'{"en":"Jerusalem"}',"region_id"=>9,],
            ["code"=>"PS", "name"=>'{"en":"Palestine"}',"region_id"=>10,],
            ["code"=>"EL", "name"=>'{"en":"Eilat"}',"region_id"=>1,],
        ]);

        DB::table('cities')->insert([
            ["code"=>'DSJ', "name"=>'{"en":"Dead sea"}',"country_id"=>94],
            ["code"=>'PET', "name"=>'{"en":"Petra"}',"country_id"=>94],
            ["code"=>'MDB', "name"=>'{"en":"Madaba"}',"country_id"=>94],
            ["code"=>'RUM', "name"=>'{"en":"Wadi rum"}',"country_id"=>94],
            ["code"=>'AJL', "name"=>'{"en":"Ajloun"}',"country_id"=>94],
            ["code"=>'AQJ', "name"=>'{"en":"Aqaba"}',"country_id"=>94],
            ["code"=>'JRJ', "name"=>'{"en":"Jerash"}',"country_id"=>94],
            ["code"=>'KRK', "name"=>'{"en":"Kerak"}',"country_id"=>94],
            ["code"=>'AZK', "name"=>'{"en":"Azrak"}',"country_id"=>94],
            ["code"=>'MAN', "name"=>'{"en":"Ma\'in"}',"country_id"=>94],
            ["code"=>'RAM', "name"=>'{"en":"Ramtha"}',"country_id"=>94],
            ["code"=>'SHK', "name"=>'{"en":"Sheikh hussein bridge"}',"country_id"=>94],
            ["code"=>'DAN', "name"=>'{"en":"Dana"}',"country_id"=>94],
            ["code"=>'ALL', "name"=>'{"en":"Allenby bridge"}',"country_id"=>94],
            ["code"=>'PEL', "name"=>'{"en":"Pella"}',"country_id"=>94],
            ["code"=>'UMQ', "name"=>'{"en":"Um qies"}',"country_id"=>94],
            ["code"=>'FEY', "name"=>'{"en":"Feynan"}',"country_id"=>94],
            ["code"=>'MUJ', "name"=>'{"en":"Mujib"}',"country_id"=>94],
            ["code"=>'aqa', "name"=>'{"en":"Amman Airport"}',"country_id"=>94],
            ["code"=>'WAD', "name"=>'{"en":"Wadi Araba"}',"country_id"=>94],
            ["code"=>'IND', "name"=>'{"en":"Jakarta"}',"country_id"=>85],
            ["code"=>'MAL', "name"=>'{"en":"Kulaa Lampour"}',"country_id"=>131],
            ["code"=>'NEB', "name"=>'{"en":"Nebo"}',"country_id"=>94],
            ["code"=>'JOR', "name"=>'{"en":"Tafileh"}',"country_id"=>94],
            ["code"=>'JR', "name"=>'{"en":"Jerusalem"}',"country_id"=>208],
            ["code"=>'EG', "name"=>'{"en":"Cairo"}',"country_id"=>55],
            ["code"=>'PS', "name"=>'{"en":"Tiberias"}',"country_id"=>87],
            ["code"=>'BTH', "name"=>'{"en":"Bethlehem"}',"country_id"=>87],
            ["code"=>'NZ', "name"=>'{"en":"Nazareth"}',"country_id"=>87],
            ["code"=>'TK', "name"=>'{"en":"Istanbul"}',"country_id"=>184],
            ["code"=>'JRC', "name"=>'{"en":"Jericho"}',"country_id"=>208],
            ["code"=>'ID', "name"=>'{"en":"Banduag"}',"country_id"=>85],
            ["code"=>'US', "name"=>'{"en":"New York"}',"country_id"=>191],
            ["code"=>'STH', "name"=>'{"en":"Saint Catherine"}',"country_id"=>55],
            ["code"=>'ALX', "name"=>'{"en":"Alexandaria"}',"country_id"=>55],
            ["code"=>'MUT', "name"=>'{"en":"Mutah"}',"country_id"=>94],
            ["code"=>'SHR', "name"=>'{"en":"Sharm Al-Sheikh"}',"country_id"=>55],
            ["code"=>'TEL', "name"=>'{"en":"Tel Aviv"}',"country_id"=>87],
            ["code"=>'RM', "name"=>'{"en":"Ramallah"}',"country_id"=>87],
            ["code"=>'PAR', "name"=>'{"en":"PARIS"}',"country_id"=>62],
            ["code"=>'DC', "name"=>'{"en":"Desert Castles"}',"country_id"=>94],
            ["code"=>'MT', "name"=>'{"en":"Mount Nebo"}',"country_id"=>94],
            ["code"=>'k', "name"=>'{"en":"Karak"}',"country_id"=>94],
            ["code"=>'B', "name"=>'{"en":"Bethany"}',"country_id"=>94],
            ["code"=>'WF', "name"=>'{"en":"Wadi Feynan"}',"country_id"=>94],
            ["code"=>'WM', "name"=>'{"en":"Wadi Mujib"}',"country_id"=>94],
            ["code"=>'AZ', "name"=>'{"en":"Azraq"}',"country_id"=>94],
            ["code"=>'BI', "name"=>'{"en":"Beidah"}',"country_id"=>94],
            ["code"=>'WBH', "name"=>'{"en":"Wadi Bin Hammad"}',"country_id"=>94],
            ["code"=>'WH', "name"=>'{"en":"Wadi Hassa"}',"country_id"=>94],
            ["code"=>'WG', "name"=>'{"en":"Wadi Ghuweir"}',"country_id"=>94],
            ["code"=>'RSF', "name"=>'{"en":"Ras El Feid"}',"country_id"=>94],
            ["code"=>'SHT', "name"=>'{"en":"Shkaret Masei\'d"}',"country_id"=>94],
            ["code"=>'WDB', "name"=>'{"en":"Wadi Barwas"}',"country_id"=>94],
            ["code"=>'sho', "name"=>'{"en":"Shobak"}',"country_id"=>94],
            ["code"=>'SAL', "name"=>'{"en":"Salt"}',"country_id"=>94],
            ["code"=>'JOV', "name"=>'{"en":"Jordan Valley"}',"country_id"=>94],
            ["code"=>'MUK', "name"=>'{"en":"Mukawer"}',"country_id"=>94],
            ["code"=>'UMR', "name"=>'{"en":"Um Rassas"}',"country_id"=>94],
            ["code"=>'ANJ', "name"=>'{"en":"Anjara"}',"country_id"=>94],
            ["code"=>'TME', "name"=>'{"en":"Tel Mar Elias"}',"country_id"=>94],
            ["code"=>'CAN', "name"=>'{"en":"Cana"}',"country_id"=>87],
            ["code"=>'TAB', "name"=>'{"en":"Tabgha"}',"country_id"=>87],
            ["code"=>'mtc', "name"=>'{"en":"Mount Carmel"}',"country_id"=>87],
            ["code"=>'SGL', "name"=>'{"en":"Sea of Galilee"}',"country_id"=>87],
            ["code"=>'CAS', "name"=>'{"en":"Caesarea"}',"country_id"=>87],
            ["code"=>'WAL', "name"=>'{"en":"Wailing Wall"}',"country_id"=>87],
            ["code"=>'QUM', "name"=>'{"en":"Qumran National Park"}',"country_id"=>87],
            ["code"=>'DED', "name"=>'{"en":"Dead Sea, Pl"}',"country_id"=>87],
            ["code"=>'YAD', "name"=>'{"en":"Yad Vashem"}',"country_id"=>87],
            ["code"=>'CPH', "name"=>'{"en":"Caesarea Philippi"}',"country_id"=>87],
            ["code"=>'MTH', "name"=>'{"en":"Mount Hermon"}',"country_id"=>87],
            ["code"=>'TEM', "name"=>'{"en":"Tel Megiddo"}',"country_id"=>87],
            ["code"=>'MAS', "name"=>'{"en":"Masada National Park"}',"country_id"=>87],
            ["code"=>'HAF', "name"=>'{"en":"Haifa"}',"country_id"=>87],
            ["code"=>'JAF', "name"=>'{"en":"Jaffa"}',"country_id"=>87],
            ["code"=>'MBT', "name"=>'{"en":"Mount Beatitudes"}',"country_id"=>87],
            ["code"=>'BNG', "name"=>'{"en":"Ben Gurion Airport"}',"country_id"=>87],
            ["code"=>'KDV', "name"=>'{"en":"Kidron Valley"}',"country_id"=>87],
            ["code"=>'HEB', "name"=>'{"en":"Hebron"}',"country_id"=>87],
            ["code"=>'YAF', "name"=>'{"en":"Yafa"}',"country_id"=>87],
            ["code"=>'TB', "name"=>'{"en":"Taba"}',"country_id"=>55],
            ["code"=>'7SC', "name"=>'{"en":"7 Sleeper cave"}',"country_id"=>94],
            ["code"=>'SHM', "name"=>'{"en":"Shaumari"}',"country_id"=>94],
            ["code"=>'MTB', "name"=>'{"en":"Mount Tabor"}',"country_id"=>208],
            ["code"=>'CAP', "name"=>'{"en":"Capernaum"}',"country_id"=>87],
            ["code"=>'QAA', "name"=>'{"en":"Queen Alia International Airport"}',"country_id"=>94],
            ["code"=>'MTO', "name"=>'{"en":"Mount of Olives"}',"country_id"=>87],
            ["code"=>'GET', "name"=>'{"en":"Gethsemane"}',"country_id"=>87],
            ["code"=>'AA', "name"=>'{"en":"Aqaba Airport"}',"country_id"=>94],
            ["code"=>'OLD', "name"=>'{"en":"Old City Jerusalem"}',"country_id"=>87],
            ["code"=>'TED', "name"=>'{"en":"Tel Dan"}',"country_id"=>87],
            ["code"=>'BES', "name"=>'{"en":"Beit Shean"}',"country_id"=>87],
            ["code"=>'MIG', "name"=>'{"en":"Milk Grotto"}',"country_id"=>87],
            ["code"=>'NM', "name"=>'{"en":"Nabi Musa"}',"country_id"=>87],
            ["code"=>'LP', "name"=>'{"en":"Little Petra"}',"country_id"=>94],
            ["code"=>'JAL', "name"=>'{"en":"Jabal Al Lweibdeh"}',"country_id"=>94],
            ["code"=>'RAS', "name"=>'{"en":"Rainbow Street"}',"country_id"=>94],
        ]);

        DB::table('markets')->insert([
            ["id"=>1,"name"=>'{"en":"None"}'],
            ["id"=>2,"name"=>'{"en":"Latin"}'],
            ["id"=>3,"name"=>'{"en":"Indian"}'],
            ["id"=>4,"name"=>'{"en":"Malaysian"}'],
            ["id"=>5,"name"=>'{"en":"Indonisan"}'],
            ["id"=>6,"name"=>'{"en":"Turkey"}'],
            ["id"=>7,"name"=>'{"en":"Nigerian"}'],
            ["id"=>8,"name"=>'{"en":"Jerusalem"}'],
            ["id"=>9,"name"=>'{"en":"Polish"}'],
            ["id"=>10,"name"=>'{"en":"Mexican"}'],
            ["id"=>11,"name"=>'{"en":"Chiniese"}'],
            ["id"=>12,"name"=>'{"en":"USA"}'],
        ]);

        DB::table('nationalities')->insert([
            ["name"=>'{"en":"NatName"}','market_id'=>1],
            ["name"=>'{"en":"American"}','market_id'=>1],
            ["name"=>'{"en":"German"}','market_id'=>1],
            ["name"=>'{"en":"Chinese"}','market_id'=>1],
            ["name"=>'{"en":"Netherlands"}','market_id'=>1],
            ["name"=>'{"en":"Australian"}','market_id'=>1],
            ["name"=>'{"en":"Swiss"}','market_id'=>1],
            ["name"=>'{"en":"French"}','market_id'=>1],
            ["name"=>'{"en":"Japanese"}','market_id'=>1],
            ["name"=>'{"en":"Argentine"}','market_id'=>1],
            ["name"=>'{"en":"Belgian"}','market_id'=>1],
            ["name"=>'{"en":"Russian"}','market_id'=>1],
            ["name"=>'{"en":"Romanian"}','market_id'=>1],
            ["name"=>'{"en":"Czech"}','market_id'=>1],
            ["name"=>'{"en":"Swedish"}','market_id'=>1],
            ["name"=>'{"en":"British"}','market_id'=>1],
            ["name"=>'{"en":"Indian"}','market_id'=>1],
            ["name"=>'{"en":"Italian"}','market_id'=>1],
            ["name"=>'{"en":"Canadian"}','market_id'=>1],
            ["name"=>'{"en":"Brazilian"}','market_id'=>1],
            ["name"=>'{"en":"Portuguese"}','market_id'=>1],
            ["name"=>'{"en":"Polish"}','market_id'=>1],
            ["name"=>'{"en":"Indonesian"}','market_id'=>1],
            ["name"=>'{"en":"Mexican"}','market_id'=>1],
            ["name"=>'{"en":"Malaysian"}','market_id'=>1],
            ["name"=>'{"en":"Turkish"}','market_id'=>1],
            ["name"=>'{"en":"Singapore"}','market_id'=>1],
            ["name"=>'{"en":"Kenyan"}','market_id'=>1],
            ["name"=>'{"en":"Latin American"}','market_id'=>1],
            ["name"=>'{"en":"Filipino"}','market_id'=>1],
            ["name"=>'{"en":"Hong Kong"}','market_id'=>1],
            ["name"=>'{"en":"South African"}','market_id'=>1],
            ["name"=>'{"en":"Jordanian"}','market_id'=>1],
            ["name"=>'{"en":"Philippine"}','market_id'=>1],
            ["name"=>'{"en":"Lebanon"}','market_id'=>1],
            ["name"=>'{"en":"Palestine"}','market_id'=>1],
            ["name"=>'{"en":"Colombian"}','market_id'=>1],
            ["name"=>'{"en":"Saudi Arabia"}','market_id'=>1],
            ["name"=>'{"en":"Algerian"}','market_id'=>1],
            ["name"=>'{"en":"Nigerian"}','market_id'=>1],
            ["name"=>'{"en":"Dominican Republic"}','market_id'=>1],
            ["name"=>'{"en":"Egyptian"}','market_id'=>1],
            ["name"=>'{"en":"Serbian"}','market_id'=>1],
            ["name"=>'{"en":"Costa Rica"}','market_id'=>1],
            ["name"=>'{"en":"Tunisia"}','market_id'=>1],
            ["name"=>'{"en":"New Zealand"}','market_id'=>1],
            ["name"=>'{"en":"Mouritians"}','market_id'=>1],
            ["name"=>'{"en":"Thiland"}','market_id'=>1],
            ["name"=>'{"en":"Finland"}','market_id'=>1],
            ["name"=>'{"en":"Georgia"}','market_id'=>1],
            ["name"=>'{"en":"Sri Lanka"}','market_id'=>1],
            ["name"=>'{"en":"Iraq"}','market_id'=>1],
            ["name"=>'{"en":"Syrian"}','market_id'=>1],
            ["name"=>'{"en":"Qatar"}','market_id'=>1],
            ["name"=>'{"en":"Armenian"}','market_id'=>1],
            ["name"=>'{"en":"Holand"}','market_id'=>1],
            ["name"=>'{"en":"Maldives"}','market_id'=>1],
            ["name"=>'{"en":"Kuweit"}','market_id'=>1],
            ["name"=>'{"en":"Honduran"}','market_id'=>1],
            ["name"=>'{"en":"Ecuador"}','market_id'=>1],
            ["name"=>'{"en":"Estonian"}','market_id'=>1],
            ["name"=>'{"en":"Austria"}','market_id'=>1],
            ["name"=>'{"en":"Bangladeshi"}','market_id'=>1],
            ["name"=>'{"en":"Lithuania"}','market_id'=>1],
            ["name"=>'{"en":"Peru"}','market_id'=>1],
            ["name"=>'{"en":"Norwegian"}','market_id'=>1],
            ["name"=>'{"en":"African"}','market_id'=>1],
            ["name"=>'{"en":"Danish"}','market_id'=>1],
            ["name"=>'{"en":"Slovensko"}','market_id'=>1],
            ["name"=>'{"en":"United Kingdom"}','market_id'=>1],
            ["name"=>'{"en":"Denmark"}','market_id'=>1],
            ["name"=>'{"en":"Salvador"}','market_id'=>1],
            ["name"=>'{"en":"GUATEMALA"}','market_id'=>1],
            ["name"=>'{"en":"ISRAEL"}','market_id'=>1],
        ]);

        DB::table('hotel_meals')->insert([
            ["id"=>1,"name"=>'{"en":"H.B"}',"is_bb"=>0,"is_hb"=>1,"is_fb"=>0,"is_all_inc"=>0,"is_ro"=>0],
            ["id"=>2,"name"=>'{"en":"F.B"}',"is_bb"=>0,"is_hb"=>0,"is_fb"=>1,"is_all_inc"=>0,"is_ro"=>0],
            ["id"=>3,"name"=>'{"en":"R.O"}',"is_bb"=>0,"is_hb"=>0,"is_fb"=>0,"is_all_inc"=>0,"is_ro"=>0],
            ["id"=>4,"name"=>'{"en":"Day Use"}',"is_bb"=>1,"is_hb"=>0,"is_fb"=>0,"is_all_inc"=>0,"is_ro"=>0],
        ]);

        DB::table('titles')->insert([
            ["id"=>1,"name"=>'{"en":"Miss"}'],
            ["id"=>2,"name"=>'{"en":"Mrs."}'],
            ["id"=>3,"name"=>'{"en":"Chd."}'],
            ["id"=>4,"name"=>'{"en":"Inf."}'],
            ["id"=>5,"name"=>'{"en":"Haj."}'],
            ["id"=>6,"name"=>'{"en":"Female"}'],
            ["id"=>7,"name"=>'{"en":"Male"}'],
        ]);

        DB::table('bank_details')->insert([
            ["id"=>1,"name"=>'{"en":"Housing Bank"}','currency_id'=>1,'details'=>'{"en":"Beneficiary name : ADAM TRAVEL AND TOURISM"}'],
        ]);

        DB::table('group_categories_1')->insert([
            ["id"=>1,"name"=>'{"en":"FIT"}'],
            ["id"=>2,"name"=>'{"en":"Group"}'],
            ["id"=>3,"name"=>'{"en":"MICE"}'],
        ]);

        DB::table('group_categories_2')->insert([
            ["id"=>1,"name"=>'{"en":"Adventure"}'],
            ["id"=>2,"name"=>'{"en":"Classical"}'],
            ["id"=>3,"name"=>'{"en":"Biblical"}'],
            ["id"=>4,"name"=>'{"en":"Cultural"}'],
            ["id"=>5,"name"=>'{"en":"Family"}'],
            ["id"=>6,"name"=>'{"en":"Islamic"}'],
        ]);

        DB::table('statuses')->insert([
            ["id"=>1,"name"=>'{"en":"Requested"}','code'=>'RQ'],
            ["id"=>2,"name"=>'{"en":"Waiting List"}','code'=>'WL'],
            ["id"=>3,"name"=>'{"en":"HOLD"}','code'=>'HOLD'],
            ["id"=>4,"name"=>'{"en":"Cancelled"}','code'=>'CXL'],
        ]);

        DB::table('entrances')->insert([
            ["name"=>'{"en":"Jerash"}',"adult_rate"=>10, "child_rate" =>0, "city_id"=>7],
            ["name"=>'{"en":"Ajloun"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>5],
            ["name"=>'{"en":"Um Qies"}',"adult_rate"=>5, "child_rate" =>0, "city_id"=>16],
            ["name"=>'{"en":"Pella"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>15],
            ["name"=>'{"en":"Dead Sea Spa (FIT)"}',"adult_rate"=>8.5, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Dead Sea Spa (Groups)"}',"adult_rate"=>7.0996, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Madaba"}',"adult_rate"=>1, "child_rate" =>0, "city_id"=>3],
            ["name"=>'{"en":"Mt. Nebo"}',"adult_rate"=>2, "child_rate" =>0, "city_id"=>3],
            ["name"=>'{"en":"Baptism Site"}',"adult_rate"=>12, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Dana"}',"adult_rate"=>6.379, "child_rate" =>0, "city_id"=>13],
            ["name"=>'{"en":"Kerak"}',"adult_rate"=>82, "child_rate" =>0, "city_id"=>8],
            ["name"=>'{"en":"Aqaba City Tour Castle"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>6],
            ["name"=>'{"en":"Wadi Rum"}',"adult_rate"=>5, "child_rate" =>0, "city_id"=>4],
            ["name"=>'{"en":"Petra"}',"adult_rate"=>50, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Petra 2nd Day"}',"adult_rate"=>55, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Petra 3rd Day"}',"adult_rate"=>60, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Maen"}',"adult_rate"=>15, "child_rate" =>0, "city_id"=>10],
            ["name"=>'{"en":"Desert Castles"}',"adult_rate"=>630, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"King Abdullah Mosque"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Shoubak"}',"adult_rate"=>1, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Roman Theater"}',"adult_rate"=>2, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Mukawer"}',"adult_rate"=>1.5, "child_rate" =>0, "city_id"=>4],
            ["name"=>'{"en":"Petra by Night"}',"adult_rate"=>17, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Mummy Room"}',"adult_rate"=>8, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Egyptian Musuem"}',"adult_rate"=>8, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Nile Cruise Dinner"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Giza Pyramids"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Dead Sea Touristic Beach"}',"adult_rate"=>0, "child_rate" =>2.5, "city_id"=>1],
            ["name"=>'{"en":"Departure Tax"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Amman Tourist Beach"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Tel Mar Elias"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>5],
            ["name"=>'{"en":"Ma\'in Hot Sprongs"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Wadi Al-Mujib"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Marriott Dead Sea"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Aqaba Museum"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Makawer"}',"adult_rate"=>1.5, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Um Rassas"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Archeological Museum"}',"adult_rate"=>5, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Jeep Tour (2 Hours)"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Aqaba Aquarium"}',"adult_rate"=>7, "child_rate" =>0, "city_id"=>6],
            ["name"=>'{"en":"Aqaba Snorkeling"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>6],
            ["name"=>'{"en":"Jerash"}',"adult_rate"=>10, "child_rate" =>0, "city_id"=>7],
            ["name"=>'{"en":"Ajloun"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>5],
            ["name"=>'{"en":"Um Qies"}',"adult_rate"=>5, "child_rate" =>0, "city_id"=>16],
            ["name"=>'{"en":"Pella"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>15],
            ["name"=>'{"en":"Dead Sea Spa (FIT)"}',"adult_rate"=>8.5, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Dead Sea Spa (Groups)"}',"adult_rate"=>7.0996, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Madaba"}',"adult_rate"=>1, "child_rate" =>0, "city_id"=>3],
            ["name"=>'{"en":"Mt. Nebo"}',"adult_rate"=>2, "child_rate" =>0, "city_id"=>3],
            ["name"=>'{"en":"Baptism Site"}',"adult_rate"=>12, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Dana"}',"adult_rate"=>6.379, "child_rate" =>0, "city_id"=>13],
            ["name"=>'{"en":"Kerak"}',"adult_rate"=>82, "child_rate" =>0, "city_id"=>8],
            ["name"=>'{"en":"Aqaba City Tour Castle"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>6],
            ["name"=>'{"en":"Wadi Rum"}',"adult_rate"=>5, "child_rate" =>0, "city_id"=>4],
            ["name"=>'{"en":"Petra"}',"adult_rate"=>50, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Petra 2nd Day"}',"adult_rate"=>55, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Petra 3rd Day"}',"adult_rate"=>60, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Maen"}',"adult_rate"=>15, "child_rate" =>0, "city_id"=>10],
            ["name"=>'{"en":"Desert Castles"}',"adult_rate"=>630, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"King Abdullah Mosque"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Shoubak"}',"adult_rate"=>1, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Roman Theater"}',"adult_rate"=>2, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Mukawer"}',"adult_rate"=>1.5, "child_rate" =>0, "city_id"=>4],
            ["name"=>'{"en":"Petra by Night"}',"adult_rate"=>17, "child_rate" =>0, "city_id"=>2],
            ["name"=>'{"en":"Mummy Room"}',"adult_rate"=>8, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Egyptian Musuem"}',"adult_rate"=>8, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Nile Cruise Dinner"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Giza Pyramids"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>26],
            ["name"=>'{"en":"Dead Sea Touristic Beach"}',"adult_rate"=>0, "child_rate" =>2.5, "city_id"=>1],
            ["name"=>'{"en":"Departure Tax"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Amman Tourist Beach"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Tel Mar Elias"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>5],
            ["name"=>'{"en":"Ma\'in Hot Sprongs"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Wadi Al-Mujib"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Marriott Dead Sea"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Aqaba Museum"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Makawer"}',"adult_rate"=>1.5, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Um Rassas"}',"adult_rate"=>3, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Archeological Museum"}',"adult_rate"=>5, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Jeep Tour (2 Hours)"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>1],
            ["name"=>'{"en":"Aqaba Aquarium"}',"adult_rate"=>7, "child_rate" =>0, "city_id"=>6],
            ["name"=>'{"en":"Aqaba Snorkeling"}',"adult_rate"=>0, "child_rate" =>0, "city_id"=>6],
        ]);

        DB::table('restaurant_meals')->insert([
            ["name"=>'{"en":"Lunch"}'],
            ["name"=>'{"en":"Dinner"}'],
            ["name"=>'{"en":"Lunch Box"}'],
            ["name"=>'{"en":"Dinner Box"}'],
            ["name"=>'{"en":"Breakfast Box"}'],
            ["name"=>'{"en":"Entrance Only"}'],
            ["name"=>'{"en":"Extra Breakfast"}'],
            ["name"=>'{"en":"Iftar"}'],
            ["name"=>'{"en":"Nile Cruise Dinner"}'],
            ["name"=>'{"en":"Iftar Box"}'],
        ]);

        DB::table('vehicle_types')->insert([
            ["name"=>'{"en":"Mini Van"}',"seats"=>0],
            ["name"=>'{"en":"Van 7 seats"}',"seats"=>0],
            ["name"=>'{"en":"Small Bus"}',"seats"=>0],
            ["name"=>'{"en":"Medium Bus"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus & Small Bus"}',"seats"=>0],
            ["name"=>'{"en":"Van 10 seats"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus & Van"}',"seats"=>0],
            ["name"=>'{"en":"Two Large Busses"}',"seats"=>0],
            ["name"=>'{"en":"Van"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus & Medium Bus"}',"seats"=>0],
            ["name"=>'{"en":"VIP Van"}',"seats"=>0],
            ["name"=>'{"en":"Van 15 Seats"}',"seats"=>0],
            ["name"=>'{"en":"VIP 29 Seats"}',"seats"=>0],
            ["name"=>'{"en":"Two Medium Busses"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus (58 seats)"}',"seats"=>0],
            ["name"=>'{"en":"Van 13 Seats"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus (55 Seats)"}',"seats"=>0],
            ["name"=>'{"en":"VIP Van 06 Seats"}',"seats"=>0],
            ["name"=>'{"en":"Two Van"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus & Van 10 Seats"}',"seats"=>0],
            ["name"=>'{"en":"Two VANs"}',"seats"=>0],
            ["name"=>'{"en":"Large Bus (51 seats)"}',"seats"=>0],
        ]);

        DB::table('transportation_services')->insert([
            ["name"=>'{"en":"Half Day"}',"kilo_meters"=>100,"is_extra_mileage"=>0],
            ["name"=>'{"en":"Full Day"}',"kilo_meters"=>200,"is_extra_mileage"=>0],
            ["name"=>'{"en":"Stationary"}',"kilo_meters"=>0,"is_extra_mileage"=>0],
            ["name"=>'{"en":"Airport Transfer"}',"kilo_meters"=>0,"is_extra_mileage"=>0],
            ["name"=>'{"en":"One Day Tour"}',"kilo_meters"=>0,"is_extra_mileage"=>0],
            ["name"=>'{"en":"Transfer Within 1 Hour"}',"kilo_meters"=>0,"is_extra_mileage"=>0],
            ["name"=>'{"en":"Transfer Within 1 Hour"}',"kilo_meters"=>0,"is_extra_mileage"=>0],
        ]);

        DB::table('route_groups')->insert([
            ["name"=>'{"en":"Classical Routes"}'],
            ["name"=>'{"en":"Adventural Routes"}'],
            ["name"=>'{"en":"Islamic Routes"}'],
        ]);

        DB::table('room_types')->insert([
            ["name"=>'{"en":"Sea View"}'],
            ["name"=>'{"en":"Deluxe"}'],
            ["name"=>'{"en":"Superior"}'],
            ["name"=>'{"en":"Premium"}'],
            ["name"=>'{"en":"Beach"}'],
            ["name"=>'{"en":"Suite"}'],
            ["name"=>'{"en":"Executive Suite"}'],
            ["name"=>'{"en":"Premier"}'],
            ["name"=>'{"en":"Presidential"}'],
            ["name"=>'{"en":"Pool view"}'],
            ["name"=>'{"en":"Garden Suite"}'],
            ["name"=>'{"en":"Junior Suite"}'],
            ["name"=>'{"en":"Ambassador Suite"}'],
            ["name"=>'{"en":"Business room"}'],
            ["name"=>'{"en":"Prince Suite"}'],
            ["name"=>'{"en":"Royal Suite"}'],
            ["name"=>'{"en":"Full Stars Tent"}'],
            ["name"=>'{"en":"Grand Suite"}'],
            ["name"=>'{"en":"Family Room"}'],
        ]);

        DB::table('service_classifications')->insert([
            ["name"=>'{"en":"Classical Services"}'],
            ["name"=>'{"en":"Adventural Services"}'],
            ["name"=>'{"en":"Islamic Services"}'],
        ]);

        DB::table('promotions')->insert([
            ["name"=>'{"en":"Low"}',"is_only_ro"=>0,"is_inc_bb"=>0,"is_inc_hb"=>0,"is_inc_fb"=>0,"is_inc_all"=>0,],
            ["name"=>'{"en":"Shoulder"}',"is_only_ro"=>0,"is_inc_bb"=>0,"is_inc_hb"=>0,"is_inc_fb"=>0,"is_inc_all"=>0,],
            ["name"=>'{"en":"High"}',"is_only_ro"=>0,"is_inc_bb"=>0,"is_inc_hb"=>0,"is_inc_fb"=>0,"is_inc_all"=>0,],
            ["name"=>'{"en":"Peak"}',"is_only_ro"=>0,"is_inc_bb"=>0,"is_inc_hb"=>0,"is_inc_fb"=>0,"is_inc_all"=>0,],
            ["name"=>'{"en":"Winter Promotion"}',"is_only_ro"=>0,"is_inc_bb"=>0,"is_inc_hb"=>0,"is_inc_fb"=>0,"is_inc_all"=>0,],
            ["name"=>'{"en":"Summer Promotion"}',"is_only_ro"=>0,"is_inc_bb"=>0,"is_inc_hb"=>0,"is_inc_fb"=>0,"is_inc_all"=>0,],
        ]);
    }
}
